apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertcatcher
  namespace: {{ .Values.namespace }}
  labels:
    app: alertcatcher
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: alertcatcher
  template:
    metadata:
      labels:
        app: alertcatcher
    spec:
      containers:
        - name: alertcatcher
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
